### ISSUE TITLE
visible_light showing as negative values at low light

### ISSUE THREAD

**Issue by whimsee** [adafruit/Adafruit_CircuitPython_LTR329_LTR303#2]
Putting it here more as a "does this make sense?" than anything.

I was testing the LTR329 out to replace the apds9960 sensor for my timelapse rig—the apds9960 being too fancy for a simple lux/light trigger—and I noticed that it returns negative values for the visible light reading in my not-so-dark-but-dimly-lit room ie. a 79 lux on the apds9960 is -20 on the LTR329 on default settings. Increasing the gain and exposure time just makes the negative number go up.

The reading comparisons don't really matter (different sensors and whatnot), but I'm trying to make sense of the negative reading. Peeking at the code, it does make sense (visIR - Infrared, noted below via the sample code), but it seems odd that the pure IR reading is higher than Visible + IR and, of course, a negative visible reading should mean I can't see anything... maybe. I'm not sure.

Visible + IR: 48
Infrared    : 69
Visible     : -21

**Comment by whimsee** [comment]
This had me going down a rabbit hole and it lead me to a digikey forum topic about getting the lux calculation. It apparently comes from Appendix A of the datasheet. It's missing but I guess some folks have it and derived a formula. Putting it here in case it might help.

https://forum.digikey.com/t/ltr-329-lux-calculation/15776/6

**Comment by whimsee** [comment]
Update: I ended up piecing something together based on the pseudocode indicated in the datasheet with the lux calculation and that seems to do the trick. The readings can be quite inconsistent outside of default settings, but at 1X gain, 100ms integration time, and some division to flatten the huge result, I pretty much have it where it used to be in the apds9960.

Not sure if I should do a PR since it's rather hacked together, a bit messy, and it's very different from the current implementation (no IR, just lux). But it does follow the pseudocode if anyone wants to take a crack at it.

**Comment by caternuson** [comment]
Related:
https://github.com/adafruit/Adafruit_LTR329_LTR303/issues/1

The main issue is lack of documentation on how to use the infrared channel (CH1) to correct the visible channel (CH0) to compensate for the small amount of sensitivity to infrared on CH0, i.e.:
```
visible = f(CH0, CH1)
```

Lux is different. That seems to be documented in an elusive "Appendix A" that is only available upon request from the vendor for some reason. The digikey forum link above eventually leads to code that is apparently based on that. So at some point that lux value calculation could be added here.

For this specific issue, I think the fix is going to be to remove the `visible_light` property, since:
```
visible != ch0 - ch1
```

**Comment by tekktrik** [comment]
Closed via #3
